[package]
name = "movies_db_server"
version = "0.1.0"
authors = ["Froggie <froggiefab@msn.com>"]
edition = "2018"

[dependencies]
dotenv = "0.13.0"
envy = "0.3.3"
serde = "1.0.82"
serde_derive = "1.0.82"
diesel = { version = "1.3.3", features = ["postgres"] }
diesel_derives = "1.3.0"
rocket="0.4.0"